[[plugins]]
package = "netlify-plugin-a11y"

  [plugins.inputs]

  checkPaths = [
    '/index.html',
    '/html/index.html',
    '/css/properties/index.html',
    '/html/elements/a/index.html'
  ]

  debugMode = true
[[redirects]]
  from = "/css/selectors/:not()"
  to = "/css/selectors/not"
[[redirects]]
  from = "/css/selectors/::marker"
  to = "/css/selectors/marker"
[[redirects]]
  from = "/css/selectors/:nth-child()"
  to = "/css/selectors/nth-child"
[[redirects]]
  from = "/css/selectors/:nth-last-child()"
  to = "/css/selectors/nth-last-child"
