[[redirects]]
  from = "/css/selectors/:not()"
  to = "/css/selectors/not"
[[redirects]]
  from = "/css/selectors/::marker"
  to = "/css/selectors/marker"
[[redirects]]
  from = "/css/selectors/:nth-child()"
  to = "/css/selectors/nth-child"
[[redirects]]
  from = "/css/selectors/:nth-last-child()"
  to = "/css/selectors/nth-last-child"
[[redirects]]
  from = "/css/properties/color-values/"
  to = "/css/properties/lch/"
